### ISSUE TITLE
Segmentation fault if preferences.ini is not found

### ISSUE THREAD

**Issue by dunatotatos** [kaochen/SokoRobot#1]
After the installation process described in the README.md, if I run SokoRobot with `$PWD` being something else than the project root directory, preferences.ini is not found, and a `Segmentation fault` is raised :
```
bin$ ./SokoRobot 
Error opening preferences.ini: No such file or directory
Segmentation fault
```

SokoRobot should check harder to find the preferences.ini file, and should correctly handle the case when the file is not found.

**Comment by kaochen** [comment]
Hi and thanks for the remarks.

I see three problems here : 
- First : what's happen when the preferences.ini does not exist ? 
The program should build a new one and load it with default settings

- Second : how to handle settings with false parameter ? or juste missing.
The program need to recognize them ant put some limits.
ex : to avoid window_height = -1 or window_height = 100000000000; 

- Third : Where preferences is supposed to be ? In root application folder, in /home/user folder ?

I have just prepared the program for this type of question by using a Struct to store the preference values.  https://github.com/kaochen/SokoRobot/commit/130b0cd9053e30ab00931edf435fa262fac2d1f7
With few more patches I force the program to look into the Struct and not open and read the preferences.ini  over and over https://github.com/kaochen/SokoRobot/commit/fdb46b69a0913c92a047d4786a737c1af519daf6 , https://github.com/kaochen/SokoRobot/commit/bcfb989c6308ad5281b415ca6b531bea5b024d22 , https://github.com/kaochen/SokoRobot/commit/ecfa124093c7cd9791d49dfa5bd5fc191a9d674e

It's not finish but It's a start :)

**Comment by kaochen** [comment]
I have add the second point. The program read the display mode using SDL_GetCurrentDisplayMode and It set a max height, size and framerate. 
You can not  oversize the current display. This need more tests with a multi-screen setup. 
See : https://github.com/kaochen/SokoRobot/commit/3683df2c8bf133a88afaed65c5ed54813190a302

**Comment by kaochen** [comment]
I just fixed this issue with the commit : https://github.com/kaochen/SokoRobot/commit/67f6088360feb93e2b4544dde09c3a31e4c77163

You can be outside the folder to execute the program. It use the argv[0] variable to know where the program is starting from.

There's still a problem if the program is placed in a root folder. The session file will not be created. I should find a place to put it.

**Comment by kaochen** [comment]
I just moved the session.ini file to the user folder ~/.local/share/SokoRobot/
see: https://github.com/kaochen/SokoRobot/commit/dd486ec6aa370e29adc06a1460a0e82fb18faa57
session.ini store the game status (last level, all the finished level names...)
This patch should close this issue.
